"""Add percentage field to submissions

Revision ID: 4455188711ea
Revises: 84166866310a
Create Date: 2025-10-26 17:30:08.971484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4455188711ea'
down_revision = '84166866310a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('percentage')

    # ### end Alembic commands ###
