"""Add school_id and is_published to assignments

Revision ID: 84166866310a
Revises: aefa158e0edf
Create Date: 2025-10-26 17:20:46.940058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84166866310a'
down_revision = 'aefa158e0edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_published')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
