"""Add applications table

Revision ID: e2cc33ab4756
Revises: 47432842c86f
Create Date: 2025-10-25 21:50:23.179544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cc33ab4756'
down_revision = '47432842c86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_first_name', sa.String(length=100), nullable=False),
    sa.Column('student_last_name', sa.String(length=100), nullable=False),
    sa.Column('student_birth_date', sa.Date(), nullable=False),
    sa.Column('grade_applying_for', sa.Integer(), nullable=False),
    sa.Column('previous_school', sa.String(length=200), nullable=True),
    sa.Column('parent_first_name', sa.String(length=100), nullable=False),
    sa.Column('parent_last_name', sa.String(length=100), nullable=False),
    sa.Column('parent_email', sa.String(length=120), nullable=False),
    sa.Column('parent_phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'approved', 'rejected', 'waitlisted', name='application_status'), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_reference_number'), ['reference_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_reference_number'))

    op.drop_table('applications')
    # ### end Alembic commands ###
